=== KaiA02/MolekularDynamik/src/inputReader/simulation.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="input">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tStart" type="xs:double"/>
                            <xs:element name="tEnd" type="xs:double"/>
                            <xs:element name="deltaT" type="xs:double"/>
                            <xs:element name="inputType" type="xs:string"/>
                            <xs:element name="particleContainerType" type="xs:string"/>
                            <xs:element name="particles" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="x" type="xs:double"/>
                                        <xs:element name="y" type="xs:double"/>
                                        <xs:element name="z" type="xs:double"/>
                                        <xs:element name="velocityX" type="xs:double"/>
                                        <xs:element name="velocityY" type="xs:double"/>
                                        <xs:element name="velocityZ" type="xs:double"/>
                                        <xs:element name="mass" type="xs:double"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cuboids" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="n1" type="xs:double"/>
                                        <xs:element name="n2" type="xs:double"/>
                                        <xs:element name="n3" type="xs:double"/>
                                        <xs:element name="distance" type="xs:double"/>
                                        <xs:element name="meanVelocity" type="xs:double"/>
                                        <xs:element name="dimension" type="xs:double"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="disk" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="radius" type="xs:double"/>
                                        <xs:element name="distance" type="xs:double"/>
                                        <xs:element name="dimension" type="xs:double"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="output">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="baseName" type="xs:string"/>
                            <xs:element name="writeFrequency" type="xs:int"/>
                            <xs:element name="outputType" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="config">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="performanceMeasurement" type="xs:boolean" minOccurs="0"/>
                            <xs:element name="logLevel" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KaiA02/MolekularDynamik/input/eingabe-cube.xml
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/inputReader/simulation.xsd">
    <input>
        <tStart>0.0</tStart>
        <tEnd>10.0</tEnd>
        <deltaT>0.0005</deltaT>
        <inputType>LJF</inputType>
        <particleContainerType>no</particleContainerType>
        <r_cutoff>3.0</r_cutoff>
        <domainSizeX>0</domainSizeX>
        <domainSizeY>0</domainSizeY>
        <domainSizeZ>0</domainSizeZ>
        <boundary1Type>no</boundary1Type>
        <boundary2Type>no</boundary2Type>
        <boundary3Type>no</boundary3Type>
        <boundary4Type>no</boundary4Type>
        <boundary5Type>no</boundary5Type>
        <boundary6Type>no</boundary6Type>
        <particles>
            <x>15.0</x>
            <y>15.0</y>
            <z>0.0</z>
            <velocityX>0.0</velocityX>
            <velocityY>-10.0</velocityY>
            <velocityZ>0.0</velocityZ>
            <mass>1</mass>
        </particles>
        <particles>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
            <velocityX>0.0</velocityX>
            <velocityY>0.0</velocityY>
            <velocityZ>0.0</velocityZ>
            <mass>1</mass>

            <!-- Add more particle elements as needed -->
        </particles>
        <cuboids>

            <n1>8.0</n1>
            <n2>8.0</n2>
            <n3>1.0</n3>
            <distance>1.1225</distance>
            <meanVelocity>0.1</meanVelocity>
            <dimension>3.0</dimension>
        </cuboids>
        <cuboids>

            <n1>40.0</n1>
            <n2>8.0</n2>
            <n3>1.0</n3>
            <distance>1.1225</distance>
            <meanVelocity>0.1</meanVelocity>
            <dimension>3.0</dimension>

            <!-- Add more cuboid elements as needed -->
        </cuboids>
    </input>
    <output>
        <baseName>simulation_output</baseName>
        <writeFrequency>100</writeFrequency>
        <outputType>vtk</outputType>
    </output>
    <config>
        <performanceMeasurement>false</performanceMeasurement>
        <logLevel>info</logLevel>
    </config>
</simulation>
